version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt_server
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto_conf:/mosquitto/config 

  nodejs_app:
    build:
      context: ./nodejs_app
      dockerfile: Dockerfile 
    image: nodejs_server
    container_name: nodejs_server
    ports:
      - "8888:3000"
    depends_on:
      - mqtt
